version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfiles/app/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - RELOAD=true
      - PYTHONWARNINGS=ignore
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DEBUG=TRUE
    ports:
      - "8081:8081"
    depends_on:
      - database

  database:
    platform: linux/amd64
    build:
      context: ./Dockerfiles/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500
